name:                final-project
version:             0.1.0.0
github:              "s-enright/cs421-final-project"
license:             NCSA
author:              "Sean Enright"
maintainer:          "seanre2@illinois.edu"
copyright:           ""

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:  Please see the README on GitHub at <https://github.com/s-enright/cs421-final-project#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- parsec
- mtl

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - Parse
  - ArithPackrat

executables:
  final-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - final-project
    - parsec

  t1:
    main:                Main.hs
    source-dirs:         
      - t1
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded


tests:
  final-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - final-project
