name:                final-project
version:             0.1.0.0
github:              "s-enright/cs421-final-project"
license:             NCSA
author:              "Sean Enright"
maintainer:          "seanre2@illinois.edu"
copyright:           ""

extra-source-files:
- README.md

description:  Please see the README on GitHub at <https://github.com/s-enright/cs421-final-project#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  final-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - final-project

tests:
  final-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - final-project
